import { Products } from './productInterface';



export const PRODUCTS: Products[] = [
  {id : 1,
  name : ' Winter Jacket',
  price : 4500,
  description : 'Furry Winter Coat',
  inventry : 70,
  rating : 4.5,
  image1: '/assets/products/winterCoat.jpg',
  image2: '/assets/products/winterCoat.jpg',
  image3: '/assets/products/winterCoat.jpg',

 },
 {id : 2,
  name : 'Apple Mac Book ',
  price : 380,
  description : 'IOS laptop',
  inventry : 10,
  rating : 2.5,
  image1: '/assets/products/mackbook.jpg',
  image2: '/assets/products/mackbook.jpg',
  image3: '/assets/products/mackbook.jpg',

 },
 {id : 3,
  name : 'JBL head PHones',
  price : 26500,
  description : 'Good Head Phones',
  inventry : 90,
  rating : 5.0,
  image1: '/assets/products/headSets.jpg',
  image2: '/assets/products/headSets.jpg',
  image3: '/assets/products/headSets.jpg'

 },
 {id : 4,
  name : 'Ash Chair',
  price : 1730,
  description : 'Side Chair ',
  inventry : 50,
  rating : 2.1,
  image1: '/assets/products/ashchair.jpg',
  image2: '/assets/products/ashchair.jpg',
  image3: '/assets/products/ashchair.jpg',

 },
 {id : 5,
  name : 'Blue Bag',
  price : 1770,
  description : 'Beautiful Blue Bag',
  inventry : 15,
  rating : 2.1,
  image1: 'assets/products/blueBag.jpg',
  image2: 'assets/products/blueBag.jpg',
  image3: 'assets/products/blueBag.jpg',

 },

 {id : 6,
  name : 'Camera',
  price : 7800,
  description : 'go Pro Cam',
  inventry : 15,
  rating : 2.1,
  image1: '/assets/products/camera.jpg',
  image2: '/assets/products/camera.jpg',
  image3: '/assets/products/camera.jpg',

 },
 {id : 7,
  name : 'AirPods2',
  price : 47000,
  description : 'apple airpods 2',
  inventry : 15,
  rating : 2.1,
  image1: '/assets/products/airpods.jpg',
  image2: '/assets/products/airpods.jpg',
  image3: '/assets/products/airpods.jpg',

 },
 {id : 6,
  name : 'Camera',
  price : 7800,
  description : 'go Pro Cam',
  inventry : 15,
  rating : 2.1,
  image1: '/assets/products/camera.jpg',
  image2: '/assets/products/camera.jpg',
  image3: '/assets/products/camera.jpg',

 },
 {id : 4,
  name : 'Ash Chair',
  price : 1730,
  description : 'Side Chair ',
  inventry : 50,
  rating : 2.1,
  image1: '/assets/products/ashchair.jpg',
  image2: '/assets/products/ashchair.jpg',
  image3: '/assets/products/ashchair.jpg',

 },
 {id : 1,
  name : ' Winter Jacket',
  price : 4500,
  description : 'Furry Winter Coat',
  inventry : 70,
  rating : 4.5,
  image1: '/assets/products/winterCoat.jpg',
  image2: '/assets/products/winterCoat.jpg',
  image3: '/assets/products/winterCoat.jpg',
 },
]
