import { getLocaleEraNames } from '@angular/common';
import { Products } from './productInterface';



export const PRODUCTS: Products[] = [
  {id : 1,
  name : ' Winter Jacket',
  price : 4500,
  description : 'Furry Winter Coat',
  inventry : 70,
  rating : 4.5,
  image1: '/assets/products/winterCoat.jpg',
  image2: '/assets/products/winterCoat.jpg',
  image3: '/assets/products/winterCoat.jpg',
  images: []

 },
 {id : 2,
  name : 'Apple Mac Book ',
  price : 380,
  description : 'IOS laptop',
  inventry : 10,
  rating : 2.5,
  image1: '/assets/products/mackbook.jpg',
  image2: '/assets/products/mackbook.jpg',
  image3: '/assets/products/mackbook.jpg',
  images: []

 },
 {id : 3,
  name : 'JBL head PHones',
  price : 26500,
  description : 'Good Head Phones',
  inventry : 90,
  rating : 5.0,
  image1: '/assets/products/headSets.jpg',
  image2: '/assets/products/headSets.jpg',
  image3: '/assets/products/headSets.jpg',
  images: []

 },
 {id : 4,
  name : 'Ash Chair',
  price : 1730,
  description : 'Side Chair ',
  inventry : 50,
  rating : 2.1,
  image1: '/assets/products/ashchair.jpg',
  image2: '/assets/products/ashchair.jpg',
  image3: '/assets/products/ashchair.jpg',
  images: []

 },
 {id : 5,
  name : 'Blue Bag',
  price : 1770,
  description : 'Beautiful Blue Bag',
  inventry : 15,
  rating : 2.1,
  image1: 'assets/products/blueBag.jpg',
  image2: 'assets/products/blueBag.jpg',
  image3: 'assets/products/blueBag.jpg',
  images: [],

 },

 {id : 6,
  name : 'Camera',
  price : 7800,
  description : 'go Pro Cam',
  inventry : 15,
  rating : 2.1,
  image1: '/assets/products/camera.jpg',
  image2: '/assets/products/camera.jpg',
  image3: '/assets/products/camera.jpg',
  images: [],

 },
 {id : 7,
  name : 'AirPods2',
  price : 47000,
  description : 'apple airpods 2',
  inventry : 15,
  rating : 2.1,
  image1: '/assets/products/airpods.jpg',
  image2: '/assets/products/airpods.jpg',
  image3: '/assets/products/airpods.jpg',
  images: [],

 },
 {id : 6,
  name : 'Camera',
  price : 7800,
  description : 'go Pro Cam',
  inventry : 15,
  rating : 2.1,
  image1: '/assets/products/camera.jpg',
  image2: '/assets/products/camera.jpg',
  image3: '/assets/products/camera.jpg',
  images: [],

 },
 {id : 4,
  name : 'Ash Chair',
  price : 1730,
  description : 'Side Chair ',
  inventry : 50,
  rating : 2.1,
  image1: '/assets/products/ashchair.jpg',
  image2: '/assets/products/ashchair.jpg',
  image3: '/assets/products/ashchair.jpg',
  images: [],

 },
 {id : 1,
  name : ' Winter Jacket',
  price : 4500,
  description : 'What is Lorem Ipsum there was once a mad called david. he had girlfriend who many times, did not show as much care as he had hoped whe would. when days passed and passed and things became tougher and thougher, he ran away... there was a man in jericho called zacheous. The people were tall and he was a very short man. but The Lord looked up and said Zacheous come down',
  inventry : 70,
  rating : 4.5,
  image1: '/assets/products/winterCoat.jpg',
  image2: '/assets/products/winterCoat.jpg',
  image3: '/assets/products/winterCoat.jpg',
  images: ['hello world', 'one'],
 },
]
